export const statList = [
  {
    groupName: "gender",
    colName: [
      '여성', 
      '남성',
    ],
    counts: [208, 244,],
  },
  {
    groupName: "species",
    colName: ['Alligator', 'Anteater', 'Bear', 'Bird', 'Bull', 'Cat', 'Chicken',
    'Cow', 'Cub', 'Deer', 'Dog', 'Duck', 'Eagle', 'Elephant', 'Frog',
    'Goat', 'Gorilla', 'Hamster', 'Hippo', 'Horse', 'Kangaroo',
    'Koala', 'Lion', 'Monkey', 'Mouse', 'Octopus', 'Ostrich',
    'Penguin', 'Pig', 'Rabbit', 'Rhino', 'Sheep', 'Squirrel', 'Tiger',
    'Wolf',],
    counts: [ 7,  7, 15, 13,  6, 23,  9,  4, 16, 10, 16, 17,  9, 11, 18,  8,  9,
      8,  7, 15,  8,  9,  7,  8, 15,  3, 10, 13, 15, 20,  6, 13, 18,  7,
     11,],
  },
  {
    groupName: "personality",
    colName: [
      '느끼함', 
      '단순 활발', 
      '먹보', 
      '무뚝뚝', 
      '성숙함', 
      '아이돌', 
      '운동광', 
      '친절함',
    ],
    counts: [34, 24, 60, 55, 55, 49, 55, 59,],
  },
  {
    groupName: "hobby",
    colName: [
      '교육', 
      '놀이', 
      '운동', 
      '음악', 
      '자연', 
      '패션',
    ],
    counts: [64, 65, 66, 64, 66, 66,],
  },
  {
    groupName: "style",
    colName:  [
      '액티브', 
      '쿨', 
      '큐트', 
      '엘레강스', 
      '고져스', 
      '심플',
    ],
    counts: [ 
      50,  
      68,  
      63,  
      54,  
      38, 
      118, 
    ],
  },
]